# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1dc902a349c2111d04ee95eec42e9e4072e7742bf953507a8fcc338b06ca5bee5b2eb3fb8c7750ab9cff07b261a56187f06c38c315cfdc373cfc3e89bc4b858

test:
  secret_key_base: bc69af42e0340fc2704a5420fa9996343d0c3d1f90169a486b8587e71b3dbfb834ea192ba9c4d1915b339f704392dccc716341e0a5849ac7e055628579661199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
